spring:
  jackson:
    read-unknown-enum-values-as-null: true
  mongodb:
    uri: ${MONGODB_URI}

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET}
  #3600000=1hr, 28800000=8hrs, 86400000=24hrs

  expiration: ${JWT_EXPIRATION:86400000}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  level:
    br.com.officyna: ${LOG_LEVEL_APP:INFO}
    org.springframework.security: ${LOG_LEVEL_SECURITY:INFO}

