apiVersion: v1
kind: ConfigMap
metadata:
  name: officyna-config
  namespace: officyna
  labels:
    app.kubernetes.io/name: officyna
data:
  SPRING_PROFILES_ACTIVE: "default"
  JWT_EXPIRATION: "86400000"
  MANAGEMENT_HEALTH_MONGO_ENABLED: "false"