apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-declarative-config
  labels:
    app.kubernetes.io/name: kong
  namespace: officyna
data:
  kong.yml: |
    _format_version: "2.1"
    services:
      - name: officyna-service
        url: http://officyna-service:80
        routes:
          - name: officyna-route
            paths:
              - "/"
    plugins: []
