apiVersion: v1
kind: Service
metadata:
  name: kong-admin
  labels:
    app.kubernetes.io/name: kong
  namespace: officyna
spec:
  # RECOMENDO: alterar para ClusterIP em produção e proteger com ALB/ingress/VPN
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: kong
  ports:
    - name: admin-http
      port: 8001
      targetPort: 8001
      protocol: TCP
    - name: admin-gui
      port: 8002
      targetPort: 8002
      protocol: TCP
