apiVersion: v1
kind: Secret
metadata:
  name: officyna-secret
  labels:
    app.kubernetes.io/name: officyna
  namespace: officyna
type: Opaque
stringData:
  MONGODB_URI: "${MONGODB_URI}"
  JWT_SECRET: "${JWT_SECRET}"