apiVersion: v1
kind: Service
metadata:
  name: officyna-service
  labels:
    app.kubernetes.io/name: officyna
    app.kubernetes.io/component: api
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: officyna
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
      appProtocol: http