name: Destruir Infraestrutura (AWS)

# O workflow_dispatch permite que você dispare essa action MANUAMENTE
# através de um botão na interface do GitHub. Ela não vai rodar sozinha.
on:
  workflow_dispatch:

jobs:
  destroy-db:
    name: Destruir Banco de Dados e Rede (Terraform)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configurar Credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Certifique-se de que é a região correta

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        # O -auto-approve destrói sem pedir confirmação de "yes"
        run: terraform destroy -auto-approve -var="db_password=${{ secrets.DB_PASSWORD }}"