name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - developer
      - feat/144-infra-aws-kong
  pull_request:
    branches:
      - main
      - developer

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: ghcr.io/officyna/officyna-service
  JAVA_VERSION: "21"

jobs:
  build-test:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    name: Build e Testes
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar JDK ${{ env.JAVA_VERSION }} (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      - name: Compilar e executar testes (mvn verify)
        run: mvn --batch-mode --update-snapshots verify

      - name: Análise de qualidade (SonarCloud)
        if: ${{ env.SONAR_TOKEN != '' }}
        run: |
          mvn --batch-mode sonar:sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=officyna \
            -Dsonar.projectKey=officyna-service

      - name: Publicar relatório de testes
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            target/surefire-reports/
            target/failsafe-reports/
          if-no-files-found: ignore

  docker:
    name: Build e Push da Imagem Docker
    runs-on: ubuntu-latest
    needs: build-test
    if: github.event_name == 'push'
    permissions:
      contents: read
      packages: write
    outputs:
      image_tag: ${{ steps.meta.outputs.version }}
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Definir tags e metadados da imagem
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch

      - name: Build e push da imagem
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  # ==========================================
  # JOB: Deploy da Infraestrutura (Banco)
  # ==========================================
  deploy-db:
    name: Provisionar Banco de Dados (Terraform)
    outputs:
      documentdb_endpoint: ${{ steps.db-network.outputs.endpoint }}
      vpc_id: ${{ steps.db-network.outputs.vpc_id }}
      vpc_cidr: ${{ steps.db-network.outputs.vpc_cidr }}
      subnet_ids: ${{ steps.db-network.outputs.subnet_ids }}
    runs-on: ubuntu-latest
    needs: [docker, build-test]
    if: github.event_name == 'push'
    defaults:
      run:
        working-directory: infra/db
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="db_password=${{ secrets.DB_PASSWORD }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="db_password=${{ secrets.DB_PASSWORD }}"

      - name: Capturar endpoint e rede do DocumentDB
        id: db-network
        run: |
          ENDPOINT=$(terraform output -raw docdb_endpoint)
          VPC_ID=$(terraform output -raw vpc_id)
          VPC_CIDR=$(terraform output -raw vpc_cidr)
          SUBNET_IDS=$(terraform output -json subnet_ids | jq -c .)

          echo "endpoint=$ENDPOINT" >> $GITHUB_OUTPUT
          echo "vpc_id=$VPC_ID" >> $GITHUB_OUTPUT
          echo "vpc_cidr=$VPC_CIDR" >> $GITHUB_OUTPUT
          echo "subnet_ids=$SUBNET_IDS" >> $GITHUB_OUTPUT

  # ==========================================
  # JOB: Deploy da Infraestrutura (EKS)
  # ==========================================
  deploy-eks:
    name: Provisionar EKS (Terraform)
    runs-on: ubuntu-latest
    needs: [ docker, build-test, deploy-db ]
    if: github.event_name == 'push'
    defaults:
      run:
        working-directory: infra/eks

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        env:
          VPC_ID: ${{ needs.deploy-db.outputs.vpc_id }}
          SUBNET_IDS: ${{ needs.deploy-db.outputs.subnet_ids }}
        run: |
          echo "VPC_ID=$VPC_ID"
          echo "SUBNET_IDS=$SUBNET_IDS"

          terraform plan \
            -var="vpc_id=$VPC_ID" \
            -var="subnet_ids=$SUBNET_IDS"

      - name: Terraform Apply
        env:
          VPC_ID: ${{ needs.deploy-db.outputs.vpc_id }}
          SUBNET_IDS: ${{ needs.deploy-db.outputs.subnet_ids }}
        run: |
          terraform apply -auto-approve \
            -var="vpc_id=$VPC_ID" \
            -var="subnet_ids=$SUBNET_IDS"

  # ==========================================
  # JOB: Deploy Aplicacao (Kubernetes)
  # ==========================================
  deploy-app:
    name: Deploy no Kubernetes
    runs-on: ubuntu-latest
    needs: [docker, deploy-db, deploy-eks]
    if: github.event_name == 'push'
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Atualizar kube config
        run: aws eks update-kubeconfig --name eks-officyna-service --region us-east-1

      - name: Aguardar nós prontos
        run: |
          echo "Aguardando nós prontos..."
          kubectl wait --for=condition=Ready nodes --all --timeout=600s || true

      - name: Instalar metrics-server (necessário para o HPA)
        run: |
          kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

      - name: Instalar envsubst
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext-base

      - name: Aplicar Kong (manifests)
        run: |
          kubectl create namespace officyna --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -f k8s/kong-declarative-config.yaml
          kubectl apply -f k8s/kong-deployment.yaml
          kubectl apply -f k8s/kong-service-proxy.yaml
          kubectl apply -f k8s/kong-service-admin.yaml || true

      - name: Aplicar configmap
        run: |
          kubectl apply -f k8s/configmap.yaml

      - name: Verificar URI gerada
        env:
          DOCDB_ENDPOINT: ${{ needs.deploy-db.outputs.documentdb_endpoint }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          export MONGODB_URI="mongodb://officynasoatdbuser:${DB_PASSWORD}@${DOCDB_ENDPOINT}:27017/officyna?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false"
          
          echo "$MONGODB_URI"

      - name: Mostrar secret gerado
        env:
          DOCDB_ENDPOINT: ${{ needs.deploy-db.outputs.documentdb_endpoint }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          export MONGODB_URI="mongodb://officynasoatdbuser:${DB_PASSWORD}@${DOCDB_ENDPOINT}:27017/officyna?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false"
          
          envsubst < k8s/secret.yaml

      - name: Aplicar Secret
        env:
          DOCDB_ENDPOINT: ${{ needs.deploy-db.outputs.documentdb_endpoint }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          export MONGODB_URI="mongodb://officynasoatdbuser:${DB_PASSWORD}@${DOCDB_ENDPOINT}:27017/officyna?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false"
          envsubst < k8s/secret.yaml | kubectl apply -f -

      - name: Criar imagePullSecret
        run: |
          kubectl create secret docker-registry ghcr-secret \
            --docker-server=ghcr.io \
            --docker-username=${{ secrets.GHCR_USERNAME }} \
            --docker-password=${{ secrets.GHCR_PAT }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Aplicar Deployment, Service e HPA
        run: |
          sed -i "s|image: ${IMAGE_NAME}:latest|image: ${IMAGE_NAME}:${{ needs.docker.outputs.image_tag }}|" k8s/deployment.yaml          
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/hpa.yaml

      - name: Aguardar rollout da aplicação
        run: |
          kubectl rollout status deployment/officyna-service --timeout=300s
          kubectl get pods,svc,hpa 

      - name: Logs da aplicação
        run: |
          kubectl logs deployment/officyna-service

      - name: Obter e Publicar URLs Públicas da Aplicação
        run: |
          echo "Buscando endpoint público do Kong Gateway..."
          ENDPOINT=""
          for i in $(seq 1 30); do
            ENDPOINT=$(kubectl get svc kong-proxy -n officyna -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || true)
            if [ -z "$ENDPOINT" ]; then
              ENDPOINT=$(kubectl get svc kong-proxy -n officyna -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || true)
            fi
            if [ -n "$ENDPOINT" ]; then
              break
            fi
            echo "Aguardando Load Balancer da AWS responder... (tentativa $i de 30)"
            sleep 10
          done

          if [ -z "$ENDPOINT" ]; then
            echo "⚠️ Não foi possível obter o Load Balancer a tempo."
            echo "### ⚠️ Deploy Concluído, mas o Load Balancer ainda está em provisionamento na AWS" >> $GITHUB_STEP_SUMMARY
          else
            echo "=================================================="
            echo "🎉 GATEWAY URL: http://$ENDPOINT:8000/officyna"
            echo "📚 SWAGGER UI:  http://$ENDPOINT:8000/officyna/swagger-ui/index.html"
            echo "❤️  HEALTHCHECK: http://$ENDPOINT:8000/officyna/actuator/health"
            echo "=================================================="

            echo "## 🚀 Deploy Concluído com Sucesso!" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "| Recurso | URL Pública |" >> $GITHUB_STEP_SUMMARY
            echo "| :--- | :--- |" >> $GITHUB_STEP_SUMMARY
            echo "| 🌐 **API Gateway (Kong)** | \`http://$ENDPOINT:8000/officyna\` |" >> $GITHUB_STEP_SUMMARY
            echo "| 📚 **Swagger UI** | [Abrir Swagger](http://$ENDPOINT:8000/officyna/swagger-ui/index.html) |" >> $GITHUB_STEP_SUMMARY
            echo "| ❤️ **Health Check** | [Ver Status](http://$ENDPOINT:8000/officyna/actuator/health) |" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Diagnóstico em caso de falha
        if: failure()
        run: |
          echo "===== PODS ====="
          kubectl get pods -o wide
          
          echo "===== DESCRIBE POD ====="
          kubectl describe pod -l app.kubernetes.io/name=officyna
          
          echo "===== EVENTS ====="
          kubectl get events --sort-by=.metadata.creationTimestamp

      - name: Logs do Pod
        if: failure()
        run: |
          POD=$(kubectl get pods -l app.kubernetes.io/name=officyna -o jsonpath='{.items[0].metadata.name}')
          
          echo "===== POD ====="
          echo "$POD"
          
          echo "===== LOGS ATUAIS ====="
          kubectl logs $POD || true
          
          echo "===== LOGS ANTERIORES ====="
          kubectl logs $POD --previous || true
          
          echo "===== VARIÁVEIS ====="
          kubectl describe pod $POD
  #
  #  # ==========================================
  #  # JOB: Limpeza Automática (Destruição EKS)
  #  # ==========================================

  # ==========================================
  # JOB: Limpeza Automática (Destruição)
  # ==========================================
